import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import ConvexClientProvider from "@/components/modules/ConvexClientProvider";
import { PostHogProvider } from "@/components/modules/PostHogProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Neon Binder",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Theme
            accentColor="green"
            grayColor="sage"
            radius="large"
            appearance="dark"
          >
            <PostHogProvider>
              <ConvexClientProvider>{children}</ConvexClientProvider>
            </PostHogProvider>
          </Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
